Con 2128 setup new repos
shopgate/tracking-core pull request #1
Opened 2017-08-21 11:32 UTC by Carsten89

2017-08-21 12:18 UTC, fkloes reviewed
Please update the LICENSE.md. Currently it contains placeholders for the year and the copyright owner.

2017-08-21 14:22 UTC, fkloes requested changes
- The mock data for the tests cause linter errors. Commits will be probably rejected, if we have commit hooks.
- The license comments of all files have a wrong format. A block comment starts with `/**`, not `/*`

2017-08-21 14:22 UTC, fkloes commented on plugins/Base.js
> +   *                                  needed by the inherited class
Please check the indentation

2017-08-21 14:22 UTC, fkloes commented on plugins/Base.js
> +       * @param {Function} callback  Function that is called if the event occurs
Please check the indentation for the complete JSDoc

2017-08-21 14:22 UTC, fkloes commented on plugins/Base.js
> +   * @param {string}   eventName Name of the event
Please check the indentation for the complete JSDoc

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/FbPixel.js
> +    /*eslint-disable */
This is treated as an error and might cause a rejected commit, if we introduce commit hooks. A solution - which causes some warnings - is to wrap this block into a /* eslint-disable eslint-comments/no-unlimited-disable */ block

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/FbPixel.js
> +    /*eslint-disable */
Please also insert a space after /* - same at /*eslint-enable */

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/FbPixel.js
> +   * @param {Object}  options                   Common Tracking Configuration
Please check the indentation for the complete JSDoc

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/FbPixel.js
> +     * On every page. It has no params
Please correct this comment - `On` with a small character and a `.` at the end of it.

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/FbPixel.js
> +  getParamsForAddtoCartAndWishlist(data) {
Please correct the name of the function ... AddToCart should have an upper case t

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaBase.js
> +   * Creates an ga classic child tracker
Typo `a` instead of `an`

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaClassic.js
> +/* global _gaq */
Maybe add a blank line after this line to improve readability

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaClassic.js
> +    /* eslint-disable */
This will cause commit rejections when we have commit hooks in the project

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaClassic.js
> +    /* eslint-disable */
This will cause commit rejections when we have commit hooks in the project

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaUniversal.js
> +/* global ga */
Please add a blank line afterwards to improve readability

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaUniversal.js
> +/*
Please add an additional `*`

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaUniversal.js
> + * See: https://shopgate.atlassian.net/wiki/display/CONSUMER/Google+Analytics
This link doesn't work anymore since we moved to our new Jira. If this information is still relevant, we need to move it somewhere else.

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaUniversal.js
> +   * @param {Object}  options                   Common Tracking Configuration
Please check the indentation for the complete JSDoc

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaUniversal.js
> +      /* eslint-disable */
This is treated as an eslint error and will cause rejections, if the have our commit hooks.

2017-08-21 14:22 UTC, fkloes commented on plugins/trackers/GaUniversal.js
> +    if (window.sgData.device.access === ACCESS_TYPE_APP) {
We should check if there is a better solution this this

2017-08-21 15:20 UTC, fkloes commented on core/AppHandler.js
> + * Handler for the communication between the tracking plugins and the app (LibShopgate_App)
We don't have a `LibShopgate_App` in the new system

2017-08-21 15:20 UTC, fkloes commented on core/Core.js
> +   * @param {Object} rawData   Object with tracking data for the event
Please check the indentation for the complete JSDoc

2017-08-21 15:20 UTC, fkloes commented on core/Core.js
> +    // Exit if the user opt out. but not for the explicit add or remove tracker events
Typo... big `B` at the beginning of the new sentence

2017-08-21 15:20 UTC, fkloes commented on core/Core.js
> +    /*
Please add a 2nd `*` to have a valid block comment

2017-08-21 15:20 UTC, fkloes commented on core/Core.js
> +   * @param {Object} rawData   Object with tracking data for the event
Please check the indentation for the complete JSDoc

2017-08-21 15:20 UTC, fkloes commented on core/Core.js
> +        /*
Please add a 2nd `*`

2017-08-21 15:20 UTC, fkloes commented on helpers/formatHelpers.js
> + * @param   {Object} object         The object to query
Please check the indentation for the complete JSDoc

2017-08-21 15:20 UTC, fkloes commented on helpers/formatHelpers.js
> +   * @param   {Object} currentData             The current data that shall be investigated
Please check the indentation for the complete JSDoc

2017-08-21 15:20 UTC, fkloes commented on helpers/formatHelpers.js
> +    /*
Please convert to a proper block comment

2017-08-21 15:20 UTC, fkloes commented on helpers/formatHelpers.js
> + * @param   {*}                numericValue The value that shall be converted
Please check the indentation for the complete JSDoc

2017-08-21 15:20 UTC, fkloes commented on helpers/formatHelpers.js
> +   Setup the RegExp. It matches leading and trailing occurrences
Please convert to a proper block comment

2017-08-21 15:20 UTC, kernelkiller commented on helpers/formatHelpers.js
> +function formatFavouriteListItems(products) {
I would recommend to rename this function and adjust the comment. The function is used within the `addToWishlist` `dataFormatHelper`

2017-08-21 15:20 UTC, kernelkiller commented on helpers/formatHelpers.js
> + Storage for helper functions that transforms raw data
Please convert to a proper block comment

2017-08-21 15:20 UTC, kernelkiller commented on helpers/formatHelpers.js
> +    /*
Please convert to a proper block comment

2017-08-21 15:20 UTC, kernelkiller commented on helpers/formatHelpers.js
> +   In splittedPath we have the action as the first array entry
Please convert to a proper block comment

2017-08-21 15:20 UTC, kernelkiller commented on helpers/formatHelpers.js
> +   All pages have action as type and a parsed page title without shop name as name
Please convert to a proper block comment

2017-08-21 15:20 UTC, kernelkiller commented on helpers/formatHelpers.js
> +   Category, product and product related pages should have productnumber/categorynumber as id
Please convert to a proper block comment

2017-08-21 15:20 UTC, kernelkiller commented on helpers/formatHelpers.js
> +dataFormatHelpers.setCampaignWithUrl = rawData => ({
Please add a comment

2017-08-21 15:20 UTC, kernelkiller commented on helpers/helper.js
> +/*
Please convert to a proper block comment

2017-08-21 15:20 UTC, kernelkiller commented on helpers/helper.js
> +   * @param {string} string - string to be encoded
Please correct the comment

2017-08-21 15:20 UTC, kernelkiller commented on helpers/helper.js
> +   * @param {string} incomingUrl urlToSanitize to parse
Param doc looks strange

2017-08-22 07:29 UTC, kernelkiller commented
The alias for the `tracking-helper` doesn't seem to be a good solution. Wouldn't it be better to define a "proxy module" which exports either the content of the new helpers or the content of the legacy helpers - depending on an environment variable which is set within the `webpack.config`? 

By default it could export the content of the new file, so that we only have to set this variable within the `webpack.config` of the legacy system.

2017-08-22 09:54 UTC, kernelkiller commented on core/AppHandler.js
> + * Handler for the communication between the tracking plugins and the app (LibShopgate_App)
Removed

2017-08-22 09:54 UTC, kernelkiller commented on core/Core.js
> +   * @param {Object} rawData   Object with tracking data for the event
Cahnged

2017-08-22 10:00 UTC, kernelkiller commented on core/Core.js
> +    // Exit if the user opt out. but not for the explicit add or remove tracker events
changed

2017-08-22 10:01 UTC, kernelkiller commented on core/Core.js
> +    /*
changed

2017-08-22 10:01 UTC, kernelkiller commented on core/Core.js
> +   * @param {Object} rawData   Object with tracking data for the event
changed

2017-08-22 10:01 UTC, kernelkiller commented on core/Core.js
> +        /*
changed

2017-08-22 10:03 UTC, kernelkiller commented on plugins/Base.js
> +   *                                  needed by the inherited class
changed

2017-08-22 10:03 UTC, kernelkiller commented on plugins/Base.js
> +       * @param {Function} callback  Function that is called if the event occurs
changed

2017-08-22 10:04 UTC, kernelkiller commented on plugins/Base.js
> +   * @param {string}   eventName Name of the event
changed

2017-08-22 10:05 UTC, kernelkiller commented on plugins/trackers/FbPixel.js
> +   * @param {Object}  options                   Common Tracking Configuration
changed

2017-08-22 10:08 UTC, kernelkiller commented on plugins/trackers/FbPixel.js
> +    /*eslint-disable */
changed

2017-08-22 10:08 UTC, kernelkiller commented on plugins/trackers/FbPixel.js
> +     * On every page. It has no params
changed

2017-08-22 10:09 UTC, kernelkiller commented on plugins/trackers/FbPixel.js
> +  getParamsForAddtoCartAndWishlist(data) {
done

2017-08-22 10:10 UTC, kernelkiller commented on plugins/trackers/GaBase.js
> +   * Creates an ga classic child tracker
done

2017-08-22 10:11 UTC, kernelkiller commented on plugins/trackers/GaClassic.js
> +/* global _gaq */
done

2017-08-22 10:12 UTC, kernelkiller commented on plugins/trackers/GaClassic.js
> +    /* eslint-disable */
done

2017-08-22 10:12 UTC, kernelkiller commented on plugins/trackers/GaClassic.js
> +    /* eslint-disable */
done

2017-08-22 10:13 UTC, kernelkiller commented on plugins/trackers/GaUniversal.js
> +/* global ga */
done

2017-08-22 10:13 UTC, kernelkiller commented on plugins/trackers/GaUniversal.js
> +/*
done

2017-08-22 10:14 UTC, kernelkiller commented on plugins/trackers/GaUniversal.js
> +   * @param {Object}  options                   Common Tracking Configuration
done

2017-08-22 10:16 UTC, kernelkiller commented on plugins/trackers/GaUniversal.js
> +      /* eslint-disable */
done

2017-08-22 10:19 UTC, kernelkiller commented on helpers/formatHelpers.js
> + * @param   {Object} object         The object to query
done

2017-08-22 10:19 UTC, kernelkiller commented on helpers/formatHelpers.js
> +   * @param   {Object} currentData             The current data that shall be investigated
done

2017-08-22 10:19 UTC, kernelkiller commented on helpers/formatHelpers.js
> +    /*
done

2017-08-22 10:19 UTC, kernelkiller commented on helpers/formatHelpers.js
> + * @param   {*}                numericValue The value that shall be converted
done

2017-08-22 10:21 UTC, kernelkiller commented on helpers/formatHelpers.js
> +   Setup the RegExp. It matches leading and trailing occurrences
done

2017-08-22 10:22 UTC, kernelkiller commented on helpers/formatHelpers.js
> + Storage for helper functions that transforms raw data
done

2017-08-22 10:23 UTC, kernelkiller commented on helpers/formatHelpers.js
> +   In splittedPath we have the action as the first array entry
done

2017-08-22 10:23 UTC, kernelkiller commented on helpers/formatHelpers.js
> +   All pages have action as type and a parsed page title without shop name as name
done

2017-08-22 10:23 UTC, kernelkiller commented on helpers/formatHelpers.js
> +   Category, product and product related pages should have productnumber/categorynumber as id
done

2017-08-22 10:24 UTC, kernelkiller commented on helpers/helper.js
> +/*
done

2017-08-22 10:25 UTC, kernelkiller commented on helpers/helper.js
> +   * @param {string} string - string to be encoded
done

2017-08-22 10:25 UTC, kernelkiller commented on helpers/helper.js
> +   * @param {string} incomingUrl urlToSanitize to parse
changed

2017-08-22 11:45 UTC, Carsten89 commented on plugins/Base.js
> +   *                                  needed by the inherited class
done

2017-08-22 11:49 UTC, Carsten89 commented on plugins/Base.js
> +       * @param {Function} callback  Function that is called if the event occurs
done

2017-08-22 12:09 UTC, Carsten89 commented on plugins/Base.js
> +   * @param {string}   eventName Name of the event
done

2017-08-22 12:09 UTC, Carsten89 commented on plugins/trackers/FbPixel.js
> +   * @param {Object}  options                   Common Tracking Configuration
done

2017-08-22 12:11 UTC, Carsten89 commented on plugins/trackers/GaUniversal.js
> +    if (window.sgData.device.access === ACCESS_TYPE_APP) {
maybe later...

2017-08-22 12:17 UTC, Carsten89 commented on helpers/formatHelpers.js
> +dataFormatHelpers.setCampaignWithUrl = rawData => ({
done

2017-08-23 09:46 UTC, kernelkiller commented on helpers/formatHelpers.js
> +    /*
done

2017-08-23 10:34 UTC, fkloes approved these changes

2017-08-23 10:58 UTC, merged